using Highbyte.Wrighty.Caching;
using Highbyte.Wrighty.Configuration;
using Highbyte.Wrighty.GitHub;
using Highbyte.Wrighty.Models;
using Highbyte.Wrighty.Projects;

namespace Highbyte.Wrighty.GitHubLiveTests;

public sealed class GitHubPaginationLiveTests
{
    private const string ConfigVariable = "WRIGHTY_GITHUB_LIVE_CONFIG";
    private const string CountVariable = "WRIGHTY_GITHUB_LIVE_ITEM_COUNT";
    private const string FixtureTitlePrefix = "[pagination fixture] ";

    [LiveGitHubFact]
    [Trait("Category", "GitHubLivePagination")]
    public async Task Persistent_fixture_crosses_the_real_GitHub_page_boundary()
    {
        var configPath = Environment.GetEnvironmentVariable(ConfigVariable);
        Assert.False(
            string.IsNullOrWhiteSpace(configPath),
            $"Set {ConfigVariable} to the configuration generated by the seed script.");
        configPath = Path.GetFullPath(configPath!);
        Assert.True(
            File.Exists(configPath),
            $"Live fixture configuration '{configPath}' was not found. " +
            "Run ./scripts/seed-github-pagination-fixture.sh first, then rerun this test.");

        var expectedCount = ParseExpectedCount();
        var config = await new TrackerConfigLoader().TryLoadPathAsync(
            configPath,
            CancellationToken.None);
        Assert.NotNull(config);
        Assert.Equal("github", config.Backend, ignoreCase: true);

        var process = new RecordingGhProcess(new GhProcess());
        var client = new GitHubProjectClient(new GhApi(process), new MemoryNodeIdCache());
        var expectedPages = (expectedCount + 99) / 100;

        var all = await client.ListAsync(
            config,
            null,
            null,
            ArchiveScope.All,
            CancellationToken.None);

        Assert.Equal(expectedCount, all.Count);
        Assert.Equal(expectedCount, all.Select(item => item.Number).Distinct().Count());
        Assert.All(all, item => Assert.StartsWith(FixtureTitlePrefix, item.Title));
        Assert.Equal(expectedPages, process.ListPageRequests);

        var requestsBeforeFilter = process.ListPageRequests;
        var inProgress = await client.ListAsync(
            config,
            "In Progress",
            null,
            ArchiveScope.All,
            CancellationToken.None);

        var sentinelTitle = $"{FixtureTitlePrefix}{expectedCount:0000}";
        Assert.Contains(inProgress, item => item.Title == sentinelTitle && item.Priority == "P1");
        Assert.Equal(expectedPages, process.ListPageRequests - requestsBeforeFilter);
    }

    private static int ParseExpectedCount()
    {
        var value = Environment.GetEnvironmentVariable(CountVariable) ?? "101";
        Assert.True(
            int.TryParse(value, out var result) && result > 100,
            $"{CountVariable} must be an integer greater than 100.");
        return result;
    }

    private sealed class RecordingGhProcess(IGhProcess inner) : IGhProcess
    {
        public int ListPageRequests { get; private set; }

        public async Task<GhProcessResult> RunAsync(
            IReadOnlyList<string> arguments,
            string? standardInput,
            CancellationToken cancellationToken)
        {
            if (arguments.Contains("graphql", StringComparer.Ordinal) &&
                standardInput is not null &&
                standardInput.Contains("items(first: 100", StringComparison.Ordinal) &&
                standardInput.Contains("fieldValueByName", StringComparison.Ordinal))
            {
                ListPageRequests++;
            }

            return await inner.RunAsync(arguments, standardInput, cancellationToken);
        }
    }

    private sealed class MemoryNodeIdCache : INodeIdCache
    {
        private readonly Dictionary<string, ProjectMetadata> values =
            new(StringComparer.OrdinalIgnoreCase);

        public Task<ProjectMetadata?> GetAsync(
            string key,
            CancellationToken cancellationToken) =>
            Task.FromResult(values.GetValueOrDefault(key));

        public Task PutAsync(
            string key,
            ProjectMetadata value,
            CancellationToken cancellationToken)
        {
            values[key] = value;
            return Task.CompletedTask;
        }

        public Task InvalidateAsync(
            string key,
            CancellationToken cancellationToken)
        {
            values.Remove(key);
            return Task.CompletedTask;
        }
    }
}
