using System.Text;
using Highbyte.Wrighty.Configuration;
using Highbyte.Wrighty.Errors;

namespace Highbyte.Wrighty.Initialization;

public interface IGitHubIssueFormScaffolder
{
    Task<GitHubIssueFormScaffoldResult> ScaffoldAsync(
        string workingDirectory,
        TrackerConfig config,
        string remoteName,
        CancellationToken cancellationToken);
}

public sealed record GitHubIssueFormScaffoldResult(
    IReadOnlyList<string> Actions,
    IReadOnlyList<string> ManagedPaths,
    IReadOnlyList<string> ChangedPaths);

public interface IGitHubIssueFormPublisher
{
    Task<IReadOnlyList<string>> FindPendingAsync(
        string workingDirectory,
        IReadOnlyList<string> managedPaths,
        CancellationToken cancellationToken);

    Task<IReadOnlyList<string>> PublishAsync(
        string workingDirectory,
        IReadOnlyList<string> managedPaths,
        string remoteName,
        CancellationToken cancellationToken);
}

public sealed class GitHubIssueFormScaffolder(
    IRepositoryDiscovery repositoryDiscovery,
    IGitProcess git) : IGitHubIssueFormScaffolder
{
    private const string GeneratedHeader =
        "# Generated by Wrighty. Rerun 'wrighty init' to refresh the Project reference.";
    private static readonly IssueFormDefinition[] Forms =
    [
        new(
            "wrighty-task.yml",
            "Wrighty task",
            "Wrighty backlog issue form",
            "Create backlog work without authorizing unattended worker processing",
            []),
        new(
            "wrighty-default-agent.yml",
            "Wrighty worker task (default agent)",
            "Wrighty default-agent issue form",
            "Create work explicitly authorized for processing by the worker's default agent",
            ["wrighty:auto"]),
        AgentForm("claude", "Claude"),
        AgentForm("codex", "Codex"),
        AgentForm("copilot", "Copilot")
    ];

    public async Task<GitHubIssueFormScaffoldResult> ScaffoldAsync(
        string workingDirectory,
        TrackerConfig config,
        string remoteName,
        CancellationToken cancellationToken)
    {
        var discovered = await repositoryDiscovery.DiscoverAsync(
            workingDirectory,
            remoteName,
            cancellationToken);
        if (discovered is null ||
            !string.Equals(discovered.Host, config.GitHubHost, StringComparison.OrdinalIgnoreCase) ||
            !string.Equals(discovered.Repository, config.Repository, StringComparison.OrdinalIgnoreCase))
        {
            return new GitHubIssueFormScaffoldResult(
                [
                    $"Issue forms were not created because Git remote '{remoteName}' does not identify " +
                    $"the configured repository '{config.Repository}'."
                ],
                [],
                []);
        }

        var rootResult = await git.RunAsync(
            ["-C", workingDirectory, "rev-parse", "--show-toplevel"],
            cancellationToken);
        if (rootResult.ExitCode != 0 || string.IsNullOrWhiteSpace(rootResult.StandardOutput))
        {
            return new GitHubIssueFormScaffoldResult(
                ["Issue forms were not created because the local Git repository root could not be resolved."],
                [],
                []);
        }

        var root = rootResult.StandardOutput.Trim();
        var directory = Path.Combine(root, ".github", "ISSUE_TEMPLATE");
        Directory.CreateDirectory(directory);
        var actions = new List<string>();
        var managedPaths = new List<string>();
        var changedPaths = new List<string>();
        var templates = Forms
            .Select(form => new ManagedTemplate(
                form.FileName,
                form.ActionName,
                BuildForm(config, form)))
            .Append(new ManagedTemplate(
                "config.yml",
                "Wrighty issue-template chooser configuration",
                BuildChooserConfig()));
        foreach (var template in templates)
        {
            var path = Path.Combine(directory, template.FileName);
            if (File.Exists(path))
            {
                var existing = await File.ReadAllTextAsync(path, cancellationToken);
                if (string.Equals(existing, template.Content, StringComparison.Ordinal))
                {
                    actions.Add($"{template.ActionName} is available: {path}");
                    managedPaths.Add(path);
                }
                else if (IsManagedForm(existing, template.Content))
                {
                    await File.WriteAllTextAsync(
                        path,
                        template.Content,
                        new UTF8Encoding(false),
                        cancellationToken);
                    actions.Add($"updated {template.ActionName}: {path}");
                    managedPaths.Add(path);
                    changedPaths.Add(path);
                }
                else
                {
                    actions.Add($"Did not overwrite conflicting {template.ActionName}: {path}");
                }
                continue;
            }

            await File.WriteAllTextAsync(
                path,
                template.Content,
                new UTF8Encoding(false),
                cancellationToken);
            actions.Add($"created {template.ActionName}: {path}");
            managedPaths.Add(path);
            changedPaths.Add(path);
        }

        return new GitHubIssueFormScaffoldResult(actions, managedPaths, changedPaths);
    }

    private static string BuildForm(TrackerConfig config, IssueFormDefinition form)
    {
        var lines = new List<string>
        {
            GeneratedHeader,
            $"name: {form.Name}",
            $"description: {form.Description}"
        };
        if (form.Labels.Count > 0)
        {
            lines.Add("labels:");
            lines.AddRange(form.Labels.Select(label => $"  - \"{label}\""));
        }
        lines.AddRange(
        [
            "projects:",
            $"  - \"{config.EffectiveProjectOwner}/{config.ProjectNumber}\"",
            "body:",
            "  - type: textarea",
            "    id: description",
            "    attributes:",
            "      label: Description",
            "      description: Describe the desired outcome, constraints, and verification.",
            "    validations:",
            "      required: true",
            string.Empty
        ]);
        return string.Join('\n', lines);
    }

    private static string BuildChooserConfig() => $$"""
        {{GeneratedHeader}}
        blank_issues_enabled: false

        """;

    private static bool IsManagedForm(string existing, string expected) =>
        string.Equals(
            NormalizeManagedForm(existing),
            NormalizeManagedForm(expected),
            StringComparison.Ordinal);

    private static string NormalizeManagedForm(string content)
    {
        var lines = content.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n').ToList();
        if (lines.Count > 0 && string.Equals(lines[0], GeneratedHeader, StringComparison.Ordinal))
        {
            lines.RemoveAt(0);
        }

        var projects = lines.FindIndex(line => string.Equals(line, "projects:", StringComparison.Ordinal));
        if (projects >= 0 && projects + 1 < lines.Count &&
            lines[projects + 1].StartsWith("  - \"", StringComparison.Ordinal))
        {
            lines[projects + 1] = "  - \"<wrighty-project>\"";
        }

        return string.Join('\n', lines);
    }

    private static IssueFormDefinition AgentForm(string agent, string title) => new(
        $"wrighty-{agent}.yml",
        $"Wrighty worker task ({title})",
        $"Wrighty {title} issue form",
        $"Create work explicitly authorized for unattended {title} processing",
        ["wrighty:auto", $"wrighty:agent={agent}"]);

    private sealed record IssueFormDefinition(
        string FileName,
        string Name,
        string ActionName,
        string Description,
        IReadOnlyList<string> Labels);

    private sealed record ManagedTemplate(string FileName, string ActionName, string Content);
}

public sealed class GitHubIssueFormPublisher(IGitProcess git) : IGitHubIssueFormPublisher
{
    private const string CommitMessage = "Add Wrighty issue forms";
    private static readonly HashSet<string> AllowedNames =
    [
        "config.yml",
        "wrighty-task.yml",
        "wrighty-default-agent.yml",
        "wrighty-claude.yml",
        "wrighty-codex.yml",
        "wrighty-copilot.yml"
    ];

    public async Task<IReadOnlyList<string>> FindPendingAsync(
        string workingDirectory,
        IReadOnlyList<string> managedPaths,
        CancellationToken cancellationToken)
    {
        if (managedPaths.Count == 0)
        {
            return [];
        }

        var root = await ResolveRootAsync(workingDirectory, cancellationToken);
        var relativePaths = managedPaths
            .Select(path => ValidateAndRelativize(root, path))
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();
        var status = await ReadStatusAsync(root, relativePaths, cancellationToken);
        return string.IsNullOrWhiteSpace(status) ? [] : managedPaths;
    }

    public async Task<IReadOnlyList<string>> PublishAsync(
        string workingDirectory,
        IReadOnlyList<string> managedPaths,
        string remoteName,
        CancellationToken cancellationToken)
    {
        if (managedPaths.Count == 0)
        {
            return ["No Wrighty-managed issue forms were available to publish."];
        }

        var root = await ResolveRootAsync(workingDirectory, cancellationToken);
        var relativePaths = managedPaths
            .Select(path => ValidateAndRelativize(root, path))
            .Distinct(StringComparer.Ordinal)
            .Order(StringComparer.Ordinal)
            .ToArray();
        var branch = await RunRequiredAsync(
            ["-C", root, "branch", "--show-current"],
            "ISSUE_FORM_PUBLISH_FAILED",
            "The current Git branch could not be determined.",
            cancellationToken);
        if (string.IsNullOrWhiteSpace(branch))
        {
            throw new TrackerException(
                "ISSUE_FORM_PUBLISH_FAILED",
                "Issue forms cannot be published from a detached HEAD. No files were staged.",
                5);
        }

        var status = await ReadStatusAsync(root, relativePaths, cancellationToken);
        if (string.IsNullOrWhiteSpace(status))
        {
            return ["Wrighty issue forms are already committed; no commit or push was needed."];
        }

        var addArguments = new List<string> { "-C", root, "add", "--" };
        addArguments.AddRange(relativePaths);
        await RunRequiredAsync(
            addArguments,
            "ISSUE_FORM_PUBLISH_FAILED",
            "The Wrighty issue forms could not be staged.",
            cancellationToken);

        var commitArguments = new List<string> { "-C", root, "commit", "--only", "-m", CommitMessage, "--" };
        commitArguments.AddRange(relativePaths);
        await RunRequiredAsync(
            commitArguments,
            "ISSUE_FORM_PUBLISH_FAILED",
            "The Wrighty issue-form commit failed. The selected forms may remain staged; unrelated staged files were not included.",
            cancellationToken);

        var push = await git.RunAsync(
            ["-C", root, "push", "--set-upstream", remoteName, branch.Trim()],
            cancellationToken);
        if (push.ExitCode != 0)
        {
            throw new TrackerException(
                "PARTIAL_ISSUE_FORM_PUBLISH",
                $"The Wrighty issue forms were committed locally on '{branch.Trim()}', but pushing to remote '{remoteName}' failed. Retry with 'git push --set-upstream {remoteName} {branch.Trim()}'. {DescribeFailure(push)}",
                5,
                new Dictionary<string, object?>
                {
                    ["branch"] = branch.Trim(),
                    ["remote"] = remoteName,
                    ["committed"] = true,
                    ["pushed"] = false
                });
        }

        return
        [
            $"committed Wrighty issue forms on branch '{branch.Trim()}'",
            $"pushed branch '{branch.Trim()}' to remote '{remoteName}'"
        ];
    }

    private async Task<string> ResolveRootAsync(
        string workingDirectory,
        CancellationToken cancellationToken) =>
        (await RunRequiredAsync(
            ["-C", workingDirectory, "rev-parse", "--show-toplevel"],
            "ISSUE_FORM_PUBLISH_FAILED",
            "The local Git repository root could not be resolved.",
            cancellationToken)).Trim();

    private Task<string> ReadStatusAsync(
        string root,
        IReadOnlyList<string> relativePaths,
        CancellationToken cancellationToken)
    {
        var arguments = new List<string>
        {
            "-C", root, "status", "--porcelain=v1", "--untracked-files=all", "--"
        };
        arguments.AddRange(relativePaths);
        return RunRequiredAsync(
            arguments,
            "ISSUE_FORM_PUBLISH_FAILED",
            "The issue-form Git status could not be read.",
            cancellationToken);
    }

    private async Task<string> RunRequiredAsync(
        IReadOnlyList<string> arguments,
        string code,
        string message,
        CancellationToken cancellationToken)
    {
        var result = await git.RunAsync(arguments, cancellationToken);
        if (result.ExitCode != 0)
        {
            throw new TrackerException(code, $"{message} {DescribeFailure(result)}", 5);
        }

        return result.StandardOutput;
    }

    private static string ValidateAndRelativize(string root, string path)
    {
        var expectedDirectory = Path.Combine(".github", "ISSUE_TEMPLATE");
        var name = Path.GetFileName(path);
        var relative = Path.Combine(expectedDirectory, name);
        if (!AllowedNames.Contains(name) || !File.Exists(Path.Combine(root, relative)))
        {
            throw new TrackerException(
                "ISSUE_FORM_PUBLISH_FAILED",
                $"Refusing to publish unexpected path '{path}'.",
                5);
        }

        return relative;
    }

    private static string DescribeFailure(GitProcessResult result)
    {
        var detail = string.IsNullOrWhiteSpace(result.StandardError)
            ? result.StandardOutput
            : result.StandardError;
        return string.IsNullOrWhiteSpace(detail) ? $"Git exited with code {result.ExitCode}." : detail.Trim();
    }
}
