name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Scan with SonarCloud
        uses: highbyte/sonarscan-dotnet@8642efb8793ae4a89bd1e6cdf0a1aef1e582f9bb # v2.5.1
        with:
          sonarProjectKey: highbyte_wrighty
          sonarProjectName: wrighty
          sonarOrganization: highbyte
          dotnetTestArguments: >-
            --logger trx
            --collect:"XPlat Code Coverage"
            --
            DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: >-
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"
            -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
            /d:sonar.coverage.exclusions="tests/PackageManagerManifestTests/**/*.py"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
